/*
Navicat MySQL Data Transfer

Source Server         : liaohb
Source Server Version : 50718
Source Host           : localhost:3306
Source Database       : nodejs

Target Server Type    : MYSQL
Target Server Version : 50718
File Encoding         : 65001

Date: 2017-08-01 18:35:29
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for sys_rule
-- ----------------------------
DROP TABLE IF EXISTS `sys_rule`;
CREATE TABLE `sys_rule` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '键',
  `PathName` varchar(255) NOT NULL COMMENT '路径',
  `Method` enum('option','put','post','delete','get') NOT NULL DEFAULT 'get' COMMENT '方法',
  `Status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `Content` json DEFAULT NULL COMMENT '规则内容',
  `IsSystem` tinyint(1) DEFAULT '0' COMMENT '是否系统规则',
  `CreateTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `IsTokenAccess` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否需要token才有权限能进行访问',
  `Bewrite` varchar(200) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8 COMMENT='系统规则表';

-- ----------------------------
-- Records of sys_rule
-- ----------------------------
INSERT INTO `sys_rule` VALUES ('1', '/webapi/demo', 'get', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select * from xtn_userinfo where username = \':username\' and password = \':password\'\", \"name\": \"admininfo\", \"type\": \"query\", \"isRows\": false}, {\"id\": 100, \"sql\": \"select count(1) total, sex,cityname,age from xtn_userinfo where id = :id_judge\", \"name\": \"judgeInfo_100\", \"type\": \"query\", \"isRows\": false, \"isMergeOption\": true}, {\"id\": 10, \"sql\": \"\", \"type\": \"judge\", \"judgeInfo\": {\"failMsg\": \"用户存在\", \"strByThis\": \"if((this.sex === \'男\' && this.cityname == \'上海\' ) || (this.age > 30 && this.cityname !== \'北京\')){return true;}return false;\", \"strByEval1\": \"(\':sex\' !== \'男\' && \':cityname\' == \'北京\' ) || (:age > 30 && \':cityname\' !== \'北京\')\", \"chilrenRules\": [{\"id\": 11, \"sql\": \"select * from xtn_userinfo where sex = \':sex\'\", \"name\": \"peoples_sex\", \"type\": \"query\", \"isRows\": true}, {\"id\": 12, \"sql\": \"select * from xtn_userinfo where sex = \':sex\' and cityname = \':cityname\' \", \"name\": \"peoples_sex_city\", \"type\": \"query\", \"isRows\": true}]}}, {\"id\": 2, \"sql\": \"select * from xtn_userinfo where id> :id\", \"name\": \"userlist\", \"type\": \"query\", \"isRows\": true}, {\"id\": 3, \"type\": \"beginTran\"}, {\"id\": 4, \"sql\": \"update xtn_userinfo t set t.tel=\':tel\' where t.id = :id1\", \"name\": \"update_info\", \"type\": \"update\", \"isRows\": false}, {\"id\": 5, \"sql\": \"select * from xtn_userinfo where id = :id1\", \"name\": \"id1_info\", \"type\": \"query\", \"isRows\": false}, {\"id\": 6, \"sql\": \"insert into xtn_userinfo(username,password,tel,address) values(uuid_short(),md5(now()),\':tel\',\'哈哈\');\", \"name\": \"InsertNo\", \"type\": \"insert\"}, {\"id\": 7, \"sql\": \"select * from xtn_userinfo t where t.id = :InsertNo\", \"name\": \"insert_result11\", \"type\": \"query\", \"isRows\": false}, {\"id\": 9, \"sql\": \"select count(1) total from xtn_userinfo \", \"name\": \"insert_total1\", \"type\": \"query\", \"isRows\": false}, {\"id\": 10, \"sql\": \"delete from xtn_userinfo where id = :InsertNo - 5\", \"name\": \"delete_result\", \"type\": \"delete\"}, {\"id\": 11, \"type\": \"commit\"}, {\"id\": 13, \"sql\": \"select count(1) total from xtn_userinfo \", \"name\": \"insert_total2\", \"type\": \"query\", \"isRows\": false}], \"fields\": \"username,password,id,tel,id1,id_judge\", \"result\": 1}', '1', '2017-07-17 12:25:19', '0');
INSERT INTO `sys_rule` VALUES ('2', '/webapi/manager/api/list', 'get', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select (case t.status when 1 then \'启用\' when 0 then \'禁用\' end) StatusCn,t.* from sys_rule t;\", \"type\": \"query\", \"isRows\": true}], \"fields\": \"\", \"result\": 1}', '1', '2017-07-17 12:25:19', '1');
INSERT INTO `sys_rule` VALUES ('3', '/webapi/manager/api/add', 'post', '1', '{\"rules\": [{\"id\": 1, \"type\": \"judge\", \"judgeInfo\": {\"failMsg\": \"说明ID已经传了，直接更新信息就可以了。\", \"strByEval\": \"\", \"strByThis\": \"if( this.Id > 0 ){return false;}return true;\", \"resultIndex\": 101, \"chilrenRules\": [{\"id\": 100, \"sql\": \"update sys_rule set method = \':Method\',pathname = \':PathName\',Bewrite = \':Bewrite\',\\nStatus = :Status,IsTokenAccess=:IsTokenAccess,content = \':RuleInfo\' \\n where id = :Id\", \"name\": \"InsertNo\", \"type\": \"insert\", \"judgeInfo\": {}}, {\"id\": 101, \"sql\": \"select (case t.status when 1 then \'启用\' when 0 then \'禁用\' end) StatusCn,t.* from sys_rule t where t.id = :Id\", \"name\": \"rule_info\", \"type\": \"query\", \"judgeInfo\": {}}]}}, {\"id\": 2, \"sql\": \"select count(1) total, t.Id from sys_rule t where t.method = \':Method\' and t.pathname = \':PathName\'\", \"type\": \"query\", \"isMergeOption\": true}, {\"id\": 3, \"type\": \"judge\", \"judgeInfo\": {\"failMsg\": \"规则已经存在，请直接修改就可。\", \"strByEval\": \"\", \"strByThis\": \"if(this.total>0){return false}return true;\", \"resultIndex\": 301, \"chilrenRules\": [{\"id\": 300, \"sql\": \"update sys_rule set method = \':Method\',pathname = \':PathName\',Bewrite = \':Bewrite\',\\nStatus = :Status,IsTokenAccess=:IsTokenAccess,content = \':RuleInfo\' \\n where id = :Id\", \"type\": \"update\", \"judgeInfo\": {}}, {\"id\": 301, \"sql\": \"select (case t.status when 1 then \'启用\' when 0 then \'禁用\' end) StatusCn,t.* from sys_rule t where t.id = :Id\", \"name\": \"rule_info\", \"type\": \"query\", \"judgeInfo\": {}}]}}, {\"id\": 4, \"sql\": \"insert into sys_rule(Method, PathName, status, IsTokenAccess, Bewrite ,content)values\\n(\':Method\', \':PathName\', :Status, IsTokenAccess, \':Bewrite\', \':RuleInfo\')\", \"name\": \"InsertNo\", \"type\": \"insert\"}, {\"id\": 5, \"sql\": \"select (case t.status when 1 then \'启用\' when 0 then \'禁用\' end) StatusCn,t.* from sys_rule t where t.id = :InsertNo\", \"name\": \"ruleinfo\", \"type\": \"query\"}], \"fields\": \"Method,PathName,Status,RuleInfo,Id,IsTokenAccess,Bewrite\", \"result\": 5}', '1', '2017-07-17 16:36:51', '1');
INSERT INTO `sys_rule` VALUES ('4', '/webapi/manager/api/info', 'post', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"insert into sys_rule(Method,PathName,status,content)values(\':Method\',\':PathName\',:Status,\':RuleInfo\',\':Bewrite\')\", \"name\": \"InsertNo\", \"type\": \"insert\"}], \"fields\": \"Method,PathName,Status,RuleInfo,Bewrite\", \"result\": 1}', '1', '2017-07-18 15:22:20', '1');
INSERT INTO `sys_rule` VALUES ('5', '/webapi/manager/api/info', 'put', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"update sys_rule set \\nmethod = \':Method\',pathname = \':PathName\',\\nStatus = :Status,content = \':RuleInfo\' ,Bewrite = \':Bewrite\'\\nwhere id = :Id\", \"name\": \"\", \"type\": \"update\"}], \"fields\": \"Method,PathName,Status,RuleInfo,Id,Bewrite\", \"result\": 1}', '1', '2017-07-18 15:36:17', '1');
INSERT INTO `sys_rule` VALUES ('6', '/webapi/manager/api/info', 'delete', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select isSystem from sys_rule where id = :Id\", \"type\": \"query\", \"judgeInfo\": {}, \"isMergeOption\": true}, {\"id\": 2, \"type\": \"judge\", \"judgeInfo\": {\"failMsg\": \"系统规则不能删除。\", \"strByThis\": \"if(this.isSystem === 1 ){return false;}return true;\"}}, {\"id\": 3, \"sql\": \"delete from sys_rule where id = :Id\", \"name\": \"\", \"type\": \"delete\"}], \"fields\": \"Id\", \"result\": 3}', '1', '2017-07-18 15:37:24', '1');
INSERT INTO `sys_rule` VALUES ('7', '/webapi/manager/api/info', 'get', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select * from sys_rule where id = :Id\", \"name\": \"info\", \"type\": \"query\"}], \"fields\": \"Id\", \"result\": 1}', '1', '2017-07-18 15:42:19', '1');
INSERT INTO `sys_rule` VALUES ('14', '/webapi/userinfo/user', 'delete', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"delete from xtn_userinfo where id = :id \", \"type\": \"delete\"}], \"fields\": \"id\", \"result\": 1}', '0', '2017-07-17 12:25:19', '1');
INSERT INTO `sys_rule` VALUES ('15', '/webapi/userinfo/users', 'get', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select * from xtn_userinfo t order by t.id desc\", \"name\": \"UserList\", \"type\": \"query\", \"isRows\": \"true\"}], \"fields\": \"\", \"result\": 1}', '0', '2017-07-17 12:25:19', '1');
INSERT INTO `sys_rule` VALUES ('18', '/webapi/userinfo/user', 'post', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select * from xtn_userinfo where username = \':username\' and password = \':password\'\", \"name\": \"info\", \"type\": \"query\"}], \"fields\": \"username,password\", \"result\": 1}', '0', '2017-07-18 15:48:59', '1');
INSERT INTO `sys_rule` VALUES ('19', '/webapi/userinfo/register', 'post', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select count(1) total from xtn_userinfo t where t.username = \':UserName\'\", \"name\": \"total_info\", \"type\": \"query\", \"isMergeOption\": true}, {\"id\": 2, \"type\": \"judge\", \"judgeInfo\": {\"failMsg\": \"用户名已经存在\", \"strByEval\": \"\", \"strByThis\": \"if(this.total > 0 ){return false;}return true;\"}}, {\"id\": 3, \"sql\": \"insert into xtn_userinfo(username,password,tel,address,sex,age)values(\':UserName\', \':Password\',\':Tel\',\':Address\',\'女\',23)\", \"name\": \"InsertNo\", \"type\": \"insert\"}, {\"id\": 4, \"sql\": \"select * from xtn_userinfo t where t.id = :InsertNo\", \"name\": \"userinfo\", \"type\": \"query\"}], \"fields\": \"UserName,Password,Tel,Address\", \"result\": 4}', '0', '2017-07-18 15:59:25', '1');
INSERT INTO `sys_rule` VALUES ('22', '/webapi/userinfo/test', 'post', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"insert into xtn_userinfo(username,password,tel,address)values(\':username\', \':password\',\':tel\',\':address\')\", \"name\": \"InsertNo\", \"type\": \"insert\"}, {\"id\": 2, \"sql\": \"select * from xtn_userinfo t where t.id = :InsertNo\", \"name\": \"user_info\", \"type\": \"query\"}], \"fields\": \"username,password,tel,address\", \"result\": 1}', '0', '2017-07-24 16:25:29', '1');
INSERT INTO `sys_rule` VALUES ('23', '/webapi/userinfo/login', 'post', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select count(1) total,t.Id as UserId ,concat(\'xtn_\', md5(t.username), md5(t.password)) token,t.username,t.sex,t.cityname from xtn_userinfo t where t.username = \':username\' and t.password = \':password\'\", \"name\": \"userinfo\", \"type\": \"query\", \"isMergeOption\": true}, {\"id\": 2, \"type\": \"judge\", \"judgeInfo\": {\"failMsg\": \"用户名或密码错误\", \"strByEval\": \"\", \"strByThis\": \"if(this.total === 0){return false;}return true;\"}}, {\"id\": 3, \"sql\": \"delete from sys_session where token = \':token\';\", \"type\": \"delete\"}, {\"id\": 4, \"sql\": \"insert into sys_session(token,deadline,UserId)values(\':token\',date_add(current_timestamp, interval 1 month),:UserId)\", \"name\": \"SessionId\", \"type\": \"insert\"}, {\"id\": 5, \"sql\": \"select t.id as tokenId,t.deadline,t.UserId from sys_session t where t.id = :SessionId\", \"type\": \"query\", \"isMergeOption\": true}, {\"id\": 6, \"type\": \"cache\", \"cacheInfo\": {\"token\": \"token\", \"fields\": \"token,id,deadline \"}}], \"fields\": \"username,password\", \"result\": 1}', '0', '2017-07-27 14:37:44', '0');
INSERT INTO `sys_rule` VALUES ('30', '/webapi/map/place', 'post', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"insert into xtn_map_place(userId,Latitude,Longitude,BeginDate,EndDate,Address,InviteCode,Bewrite,Name)values\\n(:UserId,:Latitude,:Longitude,:BeginDate,:EndDate,\':Address\',xtn_invite_code(6), \':Bewrite\',\':Name\')\", \"type\": \"insert\"}, {\"id\": 2, \"sql\": \"select * from xtn_map_place t where t.id = :InsertNo\", \"name\": \"map_place\", \"type\": \"query\"}], \"fields\": \"UserId,Address,BeginDate,EndDate,Latitude,Longitude,Bewrite,Name\", \"result\": 2}', '0', '2017-08-01 09:23:21', '1');
INSERT INTO `sys_rule` VALUES ('31', '/webapi/map/placelist', 'get', '1', '{\"rules\": [{\"id\": 1, \"sql\": \"select t.BeginDate*1000 BeginDate ,t.EndDate*1000 EndDate,\\nt.Id,t.UserId,t.Latitude,t.Longitude,t.Address,t.InviteCode,t.Bewrite,t.Name \\nfrom xtn_map_place t where t.userId = :UserId order by id desc\", \"type\": \"query\", \"isRows\": true}], \"result\": 1}', '0', '2017-08-01 13:52:00', '1');
